export default {uniList: ['Leeds Conservatoire',
'Leeds College of Art',
'Plymouth College of Art',
'Falmouth University',
'University of Hertfordshire',
'University of Birmingham',
'University College Birmingham',
'Newman University, Birmingham',
'Aston University',
'Birmingham City University',
'University of Bath',
'Bath Spa University',
'University of Bradford',
'Bournemouth University',
'The Arts University College At Bournemouth',
'University of Bolton',
'University of Sussex',
'University of Brighton',
'Ravensbourne',
'University of the West of England, Bristol',
'University of Bristol',
'University of Cambridge',
'University of Chester',
'Anglia Ruskin University',
'Writtle University College',
'University of Essex',
'Canterbury Christ Church University',
'University of Kent',
'Coventry University',
'University of Warwick',
'Rose Bruford College',
'University of Derby',
'University of Durham',
'University of East London',
'City University',
'London Metropolitan University',
'University of Exeter',
'University of Gloucestershire',
'Royal Agricultural University',
'University of Surrey',
'University College for the Creative Arts',
'University of Huddersfield',
'Buckinghamshire New University',
'University of Hull',
'Kingston University',
'Liverpool Hope University',
'Liverpool John Moores University',
'Edge Hill University',
'University of Liverpool',
'University of Lancaster',
'University of Leicester',
'De Montfort University',
'Loughborough University',
'Bishop Grosseteste University College Lincoln',
'University of Lincoln',
'Leeds Beckett University',
'Leeds Trinity University',
'University of Leeds',
'Northern School of Contemporary Dance',
'University of Bedfordshire',
'University of Manchester',
'Royal Northern College of Music',
'The Manchester Metropolitan University',
'University of Salford',
'Cranfield University',
'Middlesex University',
'University of Newcastle Upon Tyne',
'University of East Anglia',
'University of Northumbria At Newcastle',
'The Nottingham Trent University',
'University of Nottingham',
'University of Northampton',
'Norwich University of the Arts',
'The Royal Veterinary College',
'Royal Academy of Music',
'Royal Central School of Speech and Drama',
'University of Oxford',
'Oxford Brookes University',
'University of Plymouth',
'College of St Mark & St John',
'University of Portsmouth',
'University of Chichester',
'University of Central Lancashire',
'University of Reading',
'Sheffield Hallam University',
'University of Sheffield',
'London South Bank University',
"King's College London",
'Trinity Laban',
'University of Greenwich',
'Goldsmiths College, University of London',
'Southampton Solent University',
'University of Southampton',
'University of Winchester',
'University of Sunderland',
'Staffordshire University',
'University of Keele',
'Roehampton University',
"St George's Hospital Medical School",
'Imperial College London',
'Royal College of Music',
'Royal College of Art',
'Harper Adams University',
'Teesside University',
"St Mary's University, Twickenham",
'Royal Holloway and Bedford New College',
'Brunel University',
'University of Westminster',
'University of the Arts London',
'University of West London',
'University College London',
'Birkbeck College',
'School of Oriental and African Studies',
'Conservatoire for Dance and Drama',
'London School of Economics and Political Science',
'University of Worcester',
'University of Wolverhampton',
'University of York',
'York St John University',
'Courtauld Institute of Art',
'University of Cumbria',
'Guildhall School of Music and Drama',
'Liverpool Institute of Performing Arts',
'University of Buckingham',
'Queen Mary, University of London']}